// Plan.swift
// AgentKit
//
// SPDX-License-Identifier: MIT

import Foundation

/// An ordered collection of ``PlanStep`` values representing a multi-step execution plan.
///
/// A `Plan` is typically generated by the ``Planner`` actor from a high-level user goal.
/// Each step is executed sequentially, and the plan tracks overall progress.
///
/// ```swift
/// let plan = Plan(
///     goal: "Research Swift concurrency and write a summary",
///     steps: [
///         PlanStep(description: "Search for Swift concurrency documentation"),
///         PlanStep(description: "Read and extract key concepts"),
///         PlanStep(description: "Write a structured summary")
///     ]
/// )
/// ```
public struct Plan: Sendable, Identifiable, Codable {

    // MARK: - Properties

    /// The unique identifier for this plan.
    public let id: String

    /// The original user goal that this plan addresses.
    public let goal: String

    /// The ordered list of steps to execute.
    public var steps: [PlanStep]

    /// The timestamp when this plan was created.
    public let createdAt: Date

    // MARK: - Computed Properties

    /// The number of completed steps.
    public var completedCount: Int {
        steps.filter { $0.status == .completed }.count
    }

    /// The total number of steps.
    public var totalCount: Int {
        steps.count
    }

    /// Whether all steps have been completed successfully.
    public var isComplete: Bool {
        steps.allSatisfy { $0.status == .completed || $0.status == .skipped }
    }

    /// Whether any step has failed.
    public var hasFailed: Bool {
        steps.contains { $0.status == .failed }
    }

    /// A formatted progress string (e.g., "2/5 steps completed").
    public var progressDescription: String {
        "\(completedCount)/\(totalCount) steps completed"
    }

    // MARK: - Initialization

    /// Creates a new plan.
    ///
    /// - Parameters:
    ///   - id: Unique identifier. Defaults to a new UUID string.
    ///   - goal: The high-level goal this plan addresses.
    ///   - steps: The ordered list of execution steps.
    ///   - createdAt: Creation timestamp. Defaults to now.
    public init(
        id: String = UUID().uuidString,
        goal: String,
        steps: [PlanStep],
        createdAt: Date = Date()
    ) {
        self.id = id
        self.goal = goal
        self.steps = steps
        self.createdAt = createdAt
    }
}
